language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:gijzelaar/snap7
  - sudo apt-get update -qq
  - sudo apt-get install snap7-dev snap71
  - pip install -r test/requirements.txt --use-mirrors
install:
  - python setup.py install
script:
  - sudo nosetests


